# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'QSGather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QSGather
  pod 'AFNetworking', '3.0.0'
  pod 'SDWebImage'

  target 'QSGatherTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QSGatherUITests' do
    # Pods for testing
  end

end
