# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

# 公有库源添加
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/jasper-tien/Specs.git'

target 'QSGather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QSGather
  pod 'AFNetworking', '3.0.0'
  pod 'SDWebImage'
  
  # custom pods
  pod 'QSKLine', '0.1.2'

  target 'QSGatherTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QSGatherUITests' do
    # Pods for testing
  end

end
